### ISSUE TITLE
Cookie is not being saved

### ISSUE THREAD

**Issue by brandoncc** [fusionjs/fusion-plugin-jwt#131]
### Type of issue

Probably user error

### Description

I am using `session.set` in an RPC handler but the cookie is not being updated.

### Current behavior

The data is not saved.

### Expected behavior

The data should be present in the next request/response cycle.

### Steps to reproduce

I have this plugin:

```javascript
import {SessionToken} from 'fusion-tokens';
import {createPlugin} from 'fusion-core';

export default createPlugin({
  deps: {Session: SessionToken},
  middleware({Session}) {
    return (ctx, next) => {
      const session = Session.from(ctx);
      ctx.session = session;
      return next();
    }
  }
});
```

and this RPC handler:

```javascript
let nextId = 0;

export default {
  create: async ({title}, ctx) => {
    try {
      const {session} = ctx;
      let todos = JSON.parse(session.get('todos') || '[]');
      console.log("LOADED")
      console.log(session)

      todos = [...todos, {id: nextId++, title, completed: false}];
      session.set('todos', JSON.stringify(todos));
      console.log("ADDED")
      console.log(session);

      return {todos};
    } catch (e) {
      console.log(e.message);
    }
  },
}
```

Attempting to create a todo results in this console output:

```
LOADED
JWTSession {
  config:
   { secret: 'some-secret',
     cookieName: 'some-cookie-name',
     expires: 86400 },
  cookie:
   'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MzM0NTEzODAsImV4cCI6MTUzMzUzNzc4MH0.wl1hg-x2QxLhiOnrKOTCl-xSQ_-UECxxV8T3Gq7Cyvo',
  token: { iat: 1533451380 } }
ADDED
JWTSession {
  config:
   { secret: 'some-secret',
     cookieName: 'some-cookie-name',
     expires: 86400 },
  cookie:
   'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1MzM0NTEzODAsImV4cCI6MTUzMzUzNzc4MH0.wl1hg-x2QxLhiOnrKOTCl-xSQ_-UECxxV8T3Gq7Cyvo',
  token:
   { iat: 1533451380,
     data:
      { todos: '[{"id":3,"title":"Go to the store","completed":false}]' } } }
```

The next create also starts with no `data`. Notice the `id: 3`, although I have not deleted 1 or 2 (they were not persisted). The `iat` also never changes, but I am not sure if it is supposed to.

### Your environment

* fusion-plugin-jwt version: 1.0.5

* Node.js version (`node --version`): 10.6.0

* npm version (`npm --version`): 6.1.0

* Operating System: Mac Os

**Comment by dennisgl** [comment]
Not sure why you have a separated plugin to attach `Session` service to `ctx` (unrecommended), when your RPC handlers appear to have a direct dependency on `Session`. Dependency system is also how Fusion.js ensuring the execution order of initializations of individual plugins and middlewares in a request cycle.

Please try the following, and feel free to re-open the task with more details if the issue persists:
```
// src/rpc/handlers.js
import {createPlugin} from 'fusion-core';
import {SessionToken} from 'fusion-tokens';

export default createPlugin({
  deps: {Session: SessionToken},
  provides: ({Session}) => {
    return {
      create: async ({title}, ctx) => {
        try {
          const session = Session.from(ctx);
          let todos = JSON.parse(session.get('todos') || '[]');
          console.log('LOADED');
          console.log(session);

          todos = [...todos, {id: nextId++, title, completed: false}];
          session.set('todos', JSON.stringify(todos));
          console.log('ADDED');
          console.log(session);

          return {todos};
        } catch (e) {
          console.log(e.message);
        }
      },
    };
  },
});
```

**Comment by brandoncc** [comment]
Hi @dennisgl, I didn't realize I hadn't closed this issue. Sorry about that. I ended up going with https://github.com/brandoncc/tofu-app/blob/master/src/plugins/todos.js Which is basically what you are talking about here. I opened this issue before I had a good understanding of how the plugin system worked. Sorry for wasting your time!
