### ISSUE TITLE
Reset cookie if signature is invalid

### ISSUE THREAD

**Issue by ganemone** [fusionjs/fusion-plugin-jwt#6]
Currently if the signature is invalid on a GET request, we send an error response. This causes issues in development when developing multiple projects on `localhost:3000`. I think we should make two changes to mitigate this.

1 - The cookie name should probably be scoped to the service. The only downside here is if you wanted to share a session across multiple services. However, this could be solved by syncing up the config between the services.

2 - A request with an invalid cookie should not error. Instead, we should reset the session.

Does this sound reasonable?

**Comment by dennisgl** [comment]
1. sounds reasonable to me, services would have to share the secrets already and it makes sense to be explicit about the cookie names
2. from security standpoint failing silently doesn't sound that bad

👍
